/** Categories, tags and forum sections from the design boards. */

export const CATEGORIES = [
  {
    slug: 'aqidah',
    name: 'আকীদাহ',
    icon: 'compass',
    usedFor: ['articles', 'questions', 'videos', 'ikhtilaf'],
    order: 1,
    description: 'ঈমান ও বিশ্বাসের মূলনীতি, কুরআন ও সহিহ সুন্নাহর আলোকে।',
  },
  {
    slug: 'fiqh',
    name: 'ফিকহ',
    icon: 'scale',
    usedFor: ['articles', 'questions', 'ikhtilaf'],
    order: 2,
    description: 'ইবাদত ও লেনদেনের বিধান, দলিল ও আলিমদের মতসহ।',
  },
  {
    slug: 'ibadah',
    name: 'ইবাদত',
    icon: 'sunrise',
    usedFor: ['articles', 'questions', 'ikhtilaf'],
    order: 3,
    description: 'সালাত, সাওম, যাকাত, হজ ও দৈনন্দিন আমল।',
  },
  {
    slug: 'tazkiyah',
    name: 'তাযকিয়াহ',
    icon: 'sprout',
    usedFor: ['articles', 'questions', 'videos', 'events'],
    order: 4,
    description: 'অন্তরের পরিশুদ্ধি: অহংকার, হিংসা ও রিয়া থেকে মুক্তির পথ।',
  },
  {
    slug: 'akhlaq',
    name: 'আখলাক',
    icon: 'heart',
    usedFor: ['articles'],
    order: 5,
    description: 'সত্যবাদিতা, বিনয় ও ইনসাফের মাধ্যমে সুন্দর চরিত্র।',
  },
  {
    slug: 'muamalat',
    name: 'লেনদেন',
    icon: 'wallet',
    usedFor: ['articles', 'questions'],
    order: 6,
    description: 'হালাল উপার্জন, সুদমুক্ত লেনদেন ও ব্যবসার আদব।',
  },
  {
    slug: 'social-responsibility',
    name: 'সামাজিক দায়িত্ব',
    icon: 'users',
    usedFor: ['articles'],
    order: 7,
    description: 'প্রতিবেশী, আত্মীয় ও সমাজের প্রতি দায়িত্ব।',
  },
  {
    slug: 'family-society',
    name: 'পরিবার ও সমাজ',
    icon: 'home',
    usedFor: ['questions'],
    order: 8,
    description: 'পারিবারিক জীবন ও সামাজিক সম্পর্কের প্রশ্ন।',
  },
  {
    slug: 'tafsir',
    name: 'তাফসির',
    icon: 'book',
    usedFor: ['videos'],
    order: 9,
    description: 'কুরআনের ব্যাখ্যা ও শিক্ষা।',
  },
  {
    slug: 'seerah',
    name: 'সীরাত',
    icon: 'landmark',
    usedFor: ['videos'],
    order: 10,
    description: 'রাসূলুল্লাহ ﷺ-এর জীবন ও শিক্ষা।',
  },
  {
    slug: 'adab',
    name: 'আদব',
    icon: 'heart',
    usedFor: ['videos'],
    order: 11,
    description: 'আচরণ ও শিষ্টাচারের সুন্নাহ।',
  },
  {
    slug: 'dawah',
    name: 'দাওয়াহ',
    icon: 'mic',
    usedFor: ['videos'],
    order: 12,
    description: 'হিকমাহ ও সুন্দর উপদেশে আহ্বান।',
  },
] as const

export const TAGS = [
  { slug: 'adab', name: 'আদব' },
  { slug: 'dawah', name: 'দাওয়াহ' },
  { slug: 'ikhtilaf', name: 'ইখতিলাফ' },
  { slug: 'salah', name: 'সালাত' },
  { slug: 'iman', name: 'ঈমান' },
  { slug: 'brotherhood', name: 'ভ্রাতৃত্ব' },
  { slug: 'hadith-sciences', name: 'হাদিস' },
  { slug: 'family', name: 'পরিবার' },
]

export const FORUM_CATEGORIES = [
  {
    slug: 'aqidah-iman',
    name: 'আকীদাহ ও ঈমান',
    order: 1,
    description: 'ঈমান ও বিশ্বাস নিয়ে প্রশ্ন ও আলোচনা।',
  },
  {
    slug: 'ibadah',
    name: 'ইবাদত',
    order: 2,
    description: 'সালাত, সাওম ও দৈনন্দিন আমলের অভিজ্ঞতা।',
  },
  {
    slug: 'family-society',
    name: 'পরিবার ও সমাজ',
    order: 3,
    description: 'পরিবার, সন্তান ও সামাজিক সম্পর্ক।',
  },
  {
    slug: 'tazkiyah',
    name: 'তাযকিয়াহ',
    order: 4,
    description: 'অন্তরের পরিশুদ্ধি ও আত্মোন্নয়ন।',
  },
  { slug: 'ilm-study', name: 'ইলম ও পড়াশোনা', order: 5, description: 'বই, কোর্স ও শেখার পদ্ধতি।' },
  {
    slug: 'platform-feedback',
    name: 'প্ল্যাটফর্ম ফিডব্যাক',
    order: 6,
    description: 'Ruhama নিয়ে পরামর্শ ও মতামত।',
  },
]
