import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "home_page" ADD COLUMN "show_hero" boolean DEFAULT true;
  ALTER TABLE "home_page" ADD COLUMN "show_pledge" boolean DEFAULT true;
  ALTER TABLE "home_page" ADD COLUMN "show_journey" boolean DEFAULT true;
  ALTER TABLE "home_page" ADD COLUMN "journey_eyebrow" varchar DEFAULT 'যাত্রার ধাপ';
  ALTER TABLE "home_page" ADD COLUMN "journey_end_text" varchar DEFAULT 'এই যাত্রায় আপনি কোথায় আছেন, নিজের ড্যাশবোর্ডে চিহ্নিত করে রাখুন।';
  ALTER TABLE "home_page" ADD COLUMN "journey_end_label" varchar DEFAULT 'আমার যাত্রা দেখুন';
  ALTER TABLE "home_page" ADD COLUMN "show_values" boolean DEFAULT true;
  ALTER TABLE "home_page" ADD COLUMN "values_eyebrow" varchar DEFAULT 'আমাদের সংস্কৃতি';
  ALTER TABLE "home_page" ADD COLUMN "show_daily" boolean DEFAULT true;
  ALTER TABLE "home_page" ADD COLUMN "daily_eyebrow" varchar DEFAULT 'প্রতিদিনের পাথেয়';
  ALTER TABLE "home_page" ADD COLUMN "daily_title" varchar DEFAULT 'আজকের আয়াত ও হাদিস' NOT NULL;
  ALTER TABLE "home_page" ADD COLUMN "show_ilm" boolean DEFAULT true;
  ALTER TABLE "home_page" ADD COLUMN "ilm_eyebrow" varchar DEFAULT 'ইলম কেন্দ্র';
  ALTER TABLE "home_page" ADD COLUMN "ilm_title" varchar DEFAULT 'বিষয়ভিত্তিক জ্ঞানভান্ডার' NOT NULL;
  ALTER TABLE "home_page" ADD COLUMN "ilm_count" numeric DEFAULT 7;
  ALTER TABLE "home_page" ADD COLUMN "show_articles" boolean DEFAULT true;
  ALTER TABLE "home_page" ADD COLUMN "articles_eyebrow" varchar DEFAULT 'নতুন লেখা';
  ALTER TABLE "home_page" ADD COLUMN "articles_title" varchar DEFAULT 'সর্বশেষ প্রবন্ধ' NOT NULL;
  ALTER TABLE "home_page" ADD COLUMN "articles_count" numeric DEFAULT 3;
  ALTER TABLE "home_page" ADD COLUMN "show_ikhtilaf" boolean DEFAULT true;
  ALTER TABLE "home_page" ADD COLUMN "ikhtilaf_eyebrow" varchar DEFAULT 'ইখতিলাফ বিভাগ';
  ALTER TABLE "home_page" ADD COLUMN "ikhtilaf_title" varchar DEFAULT 'মতপার্থক্যের আদব' NOT NULL;
  ALTER TABLE "home_page" ADD COLUMN "ikhtilaf_text" varchar DEFAULT 'যেসব বিষয়ে আলিমদের মধ্যে দলিলভিত্তিক ভিন্নমত রয়েছে, সেখানে প্রতিটি মত তার দলিলসহ পাশাপাশি তুলে ধরা হয়, সমান মর্যাদায়। উদ্দেশ্য বিতর্ক জেতা নয়, বোঝা ও সম্মান করা।';
  ALTER TABLE "home_page" ADD COLUMN "show_events" boolean DEFAULT true;
  ALTER TABLE "home_page" ADD COLUMN "events_eyebrow" varchar DEFAULT 'একসাথে বসি';
  ALTER TABLE "home_page" ADD COLUMN "events_title" varchar DEFAULT 'আসন্ন মজলিস' NOT NULL;
  ALTER TABLE "home_page" ADD COLUMN "events_count" numeric DEFAULT 3;
  ALTER TABLE "home_page" ADD COLUMN "show_cta" boolean DEFAULT true;
  ALTER TABLE "home_page" ADD COLUMN "cta_primary_label" varchar DEFAULT 'যুক্ত হোন';
  ALTER TABLE "home_page" ADD COLUMN "cta_primary_href" varchar DEFAULT '/join';
  ALTER TABLE "home_page" ADD COLUMN "cta_secondary_label" varchar DEFAULT 'আগে আমাদের জানুন';
  ALTER TABLE "home_page" ADD COLUMN "cta_secondary_href" varchar DEFAULT '/about';
  ALTER TABLE "_home_page_v" ADD COLUMN "version_show_hero" boolean DEFAULT true;
  ALTER TABLE "_home_page_v" ADD COLUMN "version_show_pledge" boolean DEFAULT true;
  ALTER TABLE "_home_page_v" ADD COLUMN "version_show_journey" boolean DEFAULT true;
  ALTER TABLE "_home_page_v" ADD COLUMN "version_journey_eyebrow" varchar DEFAULT 'যাত্রার ধাপ';
  ALTER TABLE "_home_page_v" ADD COLUMN "version_journey_end_text" varchar DEFAULT 'এই যাত্রায় আপনি কোথায় আছেন, নিজের ড্যাশবোর্ডে চিহ্নিত করে রাখুন।';
  ALTER TABLE "_home_page_v" ADD COLUMN "version_journey_end_label" varchar DEFAULT 'আমার যাত্রা দেখুন';
  ALTER TABLE "_home_page_v" ADD COLUMN "version_show_values" boolean DEFAULT true;
  ALTER TABLE "_home_page_v" ADD COLUMN "version_values_eyebrow" varchar DEFAULT 'আমাদের সংস্কৃতি';
  ALTER TABLE "_home_page_v" ADD COLUMN "version_show_daily" boolean DEFAULT true;
  ALTER TABLE "_home_page_v" ADD COLUMN "version_daily_eyebrow" varchar DEFAULT 'প্রতিদিনের পাথেয়';
  ALTER TABLE "_home_page_v" ADD COLUMN "version_daily_title" varchar DEFAULT 'আজকের আয়াত ও হাদিস' NOT NULL;
  ALTER TABLE "_home_page_v" ADD COLUMN "version_show_ilm" boolean DEFAULT true;
  ALTER TABLE "_home_page_v" ADD COLUMN "version_ilm_eyebrow" varchar DEFAULT 'ইলম কেন্দ্র';
  ALTER TABLE "_home_page_v" ADD COLUMN "version_ilm_title" varchar DEFAULT 'বিষয়ভিত্তিক জ্ঞানভান্ডার' NOT NULL;
  ALTER TABLE "_home_page_v" ADD COLUMN "version_ilm_count" numeric DEFAULT 7;
  ALTER TABLE "_home_page_v" ADD COLUMN "version_show_articles" boolean DEFAULT true;
  ALTER TABLE "_home_page_v" ADD COLUMN "version_articles_eyebrow" varchar DEFAULT 'নতুন লেখা';
  ALTER TABLE "_home_page_v" ADD COLUMN "version_articles_title" varchar DEFAULT 'সর্বশেষ প্রবন্ধ' NOT NULL;
  ALTER TABLE "_home_page_v" ADD COLUMN "version_articles_count" numeric DEFAULT 3;
  ALTER TABLE "_home_page_v" ADD COLUMN "version_show_ikhtilaf" boolean DEFAULT true;
  ALTER TABLE "_home_page_v" ADD COLUMN "version_ikhtilaf_eyebrow" varchar DEFAULT 'ইখতিলাফ বিভাগ';
  ALTER TABLE "_home_page_v" ADD COLUMN "version_ikhtilaf_title" varchar DEFAULT 'মতপার্থক্যের আদব' NOT NULL;
  ALTER TABLE "_home_page_v" ADD COLUMN "version_ikhtilaf_text" varchar DEFAULT 'যেসব বিষয়ে আলিমদের মধ্যে দলিলভিত্তিক ভিন্নমত রয়েছে, সেখানে প্রতিটি মত তার দলিলসহ পাশাপাশি তুলে ধরা হয়, সমান মর্যাদায়। উদ্দেশ্য বিতর্ক জেতা নয়, বোঝা ও সম্মান করা।';
  ALTER TABLE "_home_page_v" ADD COLUMN "version_show_events" boolean DEFAULT true;
  ALTER TABLE "_home_page_v" ADD COLUMN "version_events_eyebrow" varchar DEFAULT 'একসাথে বসি';
  ALTER TABLE "_home_page_v" ADD COLUMN "version_events_title" varchar DEFAULT 'আসন্ন মজলিস' NOT NULL;
  ALTER TABLE "_home_page_v" ADD COLUMN "version_events_count" numeric DEFAULT 3;
  ALTER TABLE "_home_page_v" ADD COLUMN "version_show_cta" boolean DEFAULT true;
  ALTER TABLE "_home_page_v" ADD COLUMN "version_cta_primary_label" varchar DEFAULT 'যুক্ত হোন';
  ALTER TABLE "_home_page_v" ADD COLUMN "version_cta_primary_href" varchar DEFAULT '/join';
  ALTER TABLE "_home_page_v" ADD COLUMN "version_cta_secondary_label" varchar DEFAULT 'আগে আমাদের জানুন';
  ALTER TABLE "_home_page_v" ADD COLUMN "version_cta_secondary_href" varchar DEFAULT '/about';`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "home_page" DROP COLUMN "show_hero";
  ALTER TABLE "home_page" DROP COLUMN "show_pledge";
  ALTER TABLE "home_page" DROP COLUMN "show_journey";
  ALTER TABLE "home_page" DROP COLUMN "journey_eyebrow";
  ALTER TABLE "home_page" DROP COLUMN "journey_end_text";
  ALTER TABLE "home_page" DROP COLUMN "journey_end_label";
  ALTER TABLE "home_page" DROP COLUMN "show_values";
  ALTER TABLE "home_page" DROP COLUMN "values_eyebrow";
  ALTER TABLE "home_page" DROP COLUMN "show_daily";
  ALTER TABLE "home_page" DROP COLUMN "daily_eyebrow";
  ALTER TABLE "home_page" DROP COLUMN "daily_title";
  ALTER TABLE "home_page" DROP COLUMN "show_ilm";
  ALTER TABLE "home_page" DROP COLUMN "ilm_eyebrow";
  ALTER TABLE "home_page" DROP COLUMN "ilm_title";
  ALTER TABLE "home_page" DROP COLUMN "ilm_count";
  ALTER TABLE "home_page" DROP COLUMN "show_articles";
  ALTER TABLE "home_page" DROP COLUMN "articles_eyebrow";
  ALTER TABLE "home_page" DROP COLUMN "articles_title";
  ALTER TABLE "home_page" DROP COLUMN "articles_count";
  ALTER TABLE "home_page" DROP COLUMN "show_ikhtilaf";
  ALTER TABLE "home_page" DROP COLUMN "ikhtilaf_eyebrow";
  ALTER TABLE "home_page" DROP COLUMN "ikhtilaf_title";
  ALTER TABLE "home_page" DROP COLUMN "ikhtilaf_text";
  ALTER TABLE "home_page" DROP COLUMN "show_events";
  ALTER TABLE "home_page" DROP COLUMN "events_eyebrow";
  ALTER TABLE "home_page" DROP COLUMN "events_title";
  ALTER TABLE "home_page" DROP COLUMN "events_count";
  ALTER TABLE "home_page" DROP COLUMN "show_cta";
  ALTER TABLE "home_page" DROP COLUMN "cta_primary_label";
  ALTER TABLE "home_page" DROP COLUMN "cta_primary_href";
  ALTER TABLE "home_page" DROP COLUMN "cta_secondary_label";
  ALTER TABLE "home_page" DROP COLUMN "cta_secondary_href";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_show_hero";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_show_pledge";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_show_journey";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_journey_eyebrow";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_journey_end_text";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_journey_end_label";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_show_values";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_values_eyebrow";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_show_daily";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_daily_eyebrow";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_daily_title";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_show_ilm";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_ilm_eyebrow";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_ilm_title";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_ilm_count";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_show_articles";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_articles_eyebrow";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_articles_title";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_articles_count";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_show_ikhtilaf";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_ikhtilaf_eyebrow";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_ikhtilaf_title";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_ikhtilaf_text";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_show_events";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_events_eyebrow";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_events_title";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_events_count";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_show_cta";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_cta_primary_label";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_cta_primary_href";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_cta_secondary_label";
  ALTER TABLE "_home_page_v" DROP COLUMN "version_cta_secondary_href";`)
}
