/**
 * Builds the admin sidebar icons (run: npx tsx scripts/generate-admin-nav-icons.tsx).
 * Each menu item gets a Lucide icon as a CSS mask, so the sidebar needs no extra JavaScript and the
 * icon takes the link's colour. The output is committed; re-run after adding a collection or global.
 */
import { writeFileSync } from 'node:fs'
import path from 'node:path'

// a build-time generator: it turns Lucide glyphs into CSS for the admin menu, nothing ships from here
// eslint-disable-next-line no-restricted-imports
import {
  AlarmClock,
  BookMarked,
  Bookmark,
  BookOpen,
  BookOpenCheck,
  BookText,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  ChartLine,
  ClipboardList,
  FileText,
  Files,
  Flag,
  FolderTree,
  Gauge,
  GraduationCap,
  HandHeart,
  Heart,
  House,
  Image,
  Images,
  Inbox,
  Info,
  KeyRound,
  Layers,
  LayoutList,
  Library,
  ListVideo,
  type LucideIcon,
  Mail,
  MessageCircleQuestion,
  MessagesSquare,
  MessageSquare,
  Plug,
  Quote,
  Scale,
  ScrollText,
  Settings,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Tags,
  ThumbsUp,
  UserCheck,
  UserCog,
  UserPlus,
  Users,
  UsersRound,
  Video,
  Bell,
} from 'lucide-react'
import { createElement } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'

/** Collection and global slugs; globals are `global-<slug>` (Payload's nav ids). */
const ICONS: Record<string, LucideIcon> = {
  users: Users,
  'audit-logs': ScrollText,
  articles: FileText,
  'ikhtilaf-topics': Scale,
  series: Layers,
  questions: MessageCircleQuestion,
  'answer-votes': ThumbsUp,
  categories: FolderTree,
  tags: Tags,
  media: Image,
  people: GraduationCap,
  courses: BookOpen,
  lessons: BookOpenCheck,
  enrollments: UserCheck,
  'lesson-progress': ChartLine,
  events: CalendarDays,
  'event-registrations': ClipboardList,
  circles: UsersRound,
  'circle-meetups': CalendarClock,
  'circle-memberships': UserPlus,
  'meetup-rsvps': CalendarCheck,
  'event-recaps': Images,
  'forum-categories': LayoutList,
  'forum-threads': MessagesSquare,
  'forum-posts': MessageSquare,
  'forum-reactions': Heart,
  reports: Flag,
  bookmarks: Bookmark,
  notifications: Bell,
  'newsletter-subscribers': Mail,
  volunteers: HandHeart,
  'contact-messages': Inbox,
  'rate-limits': Gauge,
  pages: Files,
  surahs: BookText,
  ayahs: BookMarked,
  'hadith-collections': Library,
  hadiths: Quote,
  'daily-reminders': AlarmClock,
  videos: Video,
  playlists: ListVideo,
  sessions: KeyRound,
  accounts: KeyRound,
  verifications: KeyRound,
  'global-site-settings': Settings,
  'global-home-page': House,
  'global-about-page': Info,
  'global-adab-policy': ShieldCheck,
  'global-moderation-settings': ShieldAlert,
  'global-integrations': Plug,
  'global-collection-rules': SlidersHorizontal,
  'global-role-permissions': UserCog,
}

const dataUri = (Icon: LucideIcon) => {
  const svg = renderToStaticMarkup(
    createElement(Icon, { size: 24, strokeWidth: 1.75, color: '#000' }),
  ).replace(/ class="[^"]*"/, '')
  return `url("data:image/svg+xml,${encodeURIComponent(svg).replace(/'/g, '%27')}")`
}

const lines = [
  '/* Generated by scripts/generate-admin-nav-icons.tsx; do not edit by hand. */',
  '',
  `.nav__link { --rh-nav-icon: ${dataUri(FileText)}; }`,
  ...Object.entries(ICONS).map(([id, Icon]) => `#nav-${id} { --rh-nav-icon: ${dataUri(Icon)}; }`),
  '',
]

const out = path.resolve(process.cwd(), 'src/app/(payload)/admin-nav-icons.scss')
writeFileSync(out, lines.join('\n'))
console.log(`wrote ${Object.keys(ICONS).length} icons to ${path.relative(process.cwd(), out)}`)
