import type { CollectionConfig, Config, Field, Plugin } from 'payload'

/**
 * Natural Bangla labels for fields that would otherwise show English in the admin: fields declared
 * without a label (Payload then prints the field name, e.g. "Lesson Count") and fields generated by
 * plugins (Better Auth's users, sessions and accounts). Runs last, so it sees every plugin's fields.
 * A label already written in Bangla is never touched.
 */

const LABELS: Record<string, string> = {
  // content and learning
  question: 'প্রশ্ন',
  voterKey: 'ভোটার',
  value: 'ভোট',
  lessonCount: 'পাঠ সংখ্যা',
  enrolledCount: 'ভর্তি হয়েছেন',
  event: 'মজলিস',
  circle: 'সার্কেল',
  meetup: 'বৈঠক',
  course: 'কোর্স',
  lesson: 'পাঠ',
  completedAt: 'শেষ করেছেন',
  quizCorrect: 'কুইজে সঠিক',
  number: 'নম্বর',
  nameBangla: 'বাংলা নাম',
  nameArabic: 'আরবি নাম',
  nameLatin: 'ইংরেজি নাম',
  ayahCount: 'আয়াত সংখ্যা',
  hadithCount: 'হাদিস সংখ্যা',
  key: 'রেফারেন্স',
  ayah: 'আয়াত',
  hadith: 'হাদিস',
  // forum
  thread: 'আলোচনা',
  author: 'লেখক',
  status: 'অবস্থা',
  replyCount: 'উত্তর',
  reportCount: 'রিপোর্ট',
  helpfulCount: 'সহায়ক',
  lastActivityAt: 'সর্বশেষ কার্যক্রম',
  // members, notifications, newsletter
  user: 'ইউজার',
  recipient: 'প্রাপক',
  kind: 'ধরন',
  text: 'বার্তা',
  read: 'পড়া হয়েছে',
  email: 'ইমেইল',
  source: 'কোথা থেকে',
  lastActiveAt: 'সর্বশেষ সক্রিয়',
  // audit log
  action: 'কাজ',
  actor: 'কে করেছেন',
  targetCollection: 'কোন বিভাগে',
  targetId: 'আইডি',
  summary: 'বিবরণ',
  // Better Auth (users, sessions, accounts)
  name: 'নাম',
  emailVerified: 'ইমেইল যাচাই হয়েছে',
  image: 'ছবি',
  banned: 'ব্যান করা',
  banReason: 'ব্যানের কারণ',
  banExpires: 'ব্যান শেষ হবে',
  phoneNumber: 'মোবাইল',
  phoneNumberVerified: 'মোবাইল যাচাই হয়েছে',
  accounts: 'লগইন মাধ্যম',
  sessions: 'সক্রিয় সেশন',
  account: 'লগইন মাধ্যম',
  session: 'সক্রিয় সেশন',
  site: 'সাইটে',
  accountId: 'অ্যাকাউন্ট আইডি',
  providerId: 'মাধ্যম',
  accessToken: 'Access token',
  refreshToken: 'Refresh token',
  idToken: 'ID token',
  accessTokenExpiresAt: 'Access token-এর মেয়াদ',
  refreshTokenExpiresAt: 'Refresh token-এর মেয়াদ',
  scope: 'অনুমতি',
  password: 'পাসওয়ার্ড',
  expiresAt: 'মেয়াদ শেষ',
  token: 'Token',
  ipAddress: 'IP ঠিকানা',
  userAgent: 'ডিভাইস ও ব্রাউজার',
  impersonatedBy: 'অন্য অ্যাডমিন হিসেবে',
  identifier: 'শনাক্তকারী',
  createdAt: 'তৈরি হয়েছে',
  updatedAt: 'আপডেট হয়েছে',
}

/** Plugin descriptions worth keeping, in Bangla; any other English-only description is dropped. */
const DESCRIPTIONS: Record<string, string> = {
  banned: 'ব্যান করা ইউজার লগইন করতে পারবেন না।',
  banExpires: 'খালি থাকলে ব্যান স্থায়ী।',
  emailVerified: 'ইমেইলের লিংকে ক্লিক করে ঠিকানা নিশ্চিত করেছেন কিনা।',
}

/** Better Auth's own collections appear in join tables on the user page. */
const COLLECTION_LABELS: Record<string, { singular: string; plural: string }> = {
  accounts: { singular: 'লগইন মাধ্যম', plural: 'লগইন মাধ্যম' },
  sessions: { singular: 'সেশন', plural: 'সক্রিয় সেশন' },
  verifications: { singular: 'যাচাই', plural: 'যাচাই' },
  'admin-invitations': { singular: 'আমন্ত্রণ', plural: 'আমন্ত্রণ' },
}

/**
 * Secrets that must never be on screen: anyone who sees a session token or an OAuth token could use it.
 * They stay stored and working; the admin just never displays them.
 */
const SECRET_FIELDS: Record<string, string[]> = {
  sessions: ['token'],
  accounts: ['accessToken', 'refreshToken', 'idToken', 'password'],
  verifications: ['value'],
}

const hasBangla = (s: string) => /[ঀ-৿]/.test(s)

const isEnglishOnly = (value: unknown) =>
  typeof value === 'string' && value.trim() !== '' && !hasBangla(value)

function relabel(fields: Field[], secrets: string[] = []): Field[] {
  return fields.map((field) => {
    const f = { ...field } as Field & {
      name?: string
      label?: unknown
      admin?: { description?: unknown } & Record<string, unknown>
      fields?: Field[]
      tabs?: { fields: Field[] }[]
      blocks?: { fields: Field[] }[]
    }
    if (f.name && LABELS[f.name] && (f.label === undefined || isEnglishOnly(f.label))) {
      f.label = LABELS[f.name]
    }
    if (f.name && f.admin && isEnglishOnly(f.admin.description)) {
      f.admin = { ...f.admin, description: DESCRIPTIONS[f.name] }
    }
    if (f.name && secrets.includes(f.name)) {
      f.admin = { ...(f.admin ?? {}), hidden: true, disableListColumn: true }
    }
    if (f.fields) f.fields = relabel(f.fields)
    if (f.tabs) f.tabs = f.tabs.map((t) => ({ ...t, fields: relabel(t.fields) }))
    if (f.blocks) f.blocks = f.blocks.map((b) => ({ ...b, fields: relabel(b.fields) }))
    return f as Field
  })
}

export const banglaLabels: Plugin = (config: Config): Config => ({
  ...config,
  collections: (config.collections ?? []).map((c): CollectionConfig => ({
    ...c,
    ...(COLLECTION_LABELS[c.slug] ? { labels: COLLECTION_LABELS[c.slug] } : {}),
    ...(SECRET_FIELDS[c.slug] && c.admin?.defaultColumns
      ? {
          admin: {
            ...c.admin,
            defaultColumns: c.admin.defaultColumns.filter(
              (col) => !SECRET_FIELDS[c.slug]!.includes(col),
            ),
          },
        }
      : {}),
    fields: relabel(c.fields, SECRET_FIELDS[c.slug]),
  })),
  globals: (config.globals ?? []).map((g) => ({ ...g, fields: relabel(g.fields) })),
})
