/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    sessions: Session;
    accounts: Account;
    verifications: Verification;
    rateLimit: RateLimit;
    'admin-invitations': AdminInvitation;
    articles: Article;
    'ikhtilaf-topics': IkhtilafTopic;
    questions: Question;
    series: Series;
    categories: Category;
    tags: Tag;
    people: Person;
    courses: Course;
    lessons: Lesson;
    events: Event;
    'event-registrations': EventRegistration;
    circles: Circle;
    'circle-meetups': CircleMeetup;
    'circle-memberships': CircleMembership;
    'meetup-rsvps': MeetupRsvp;
    videos: Video;
    playlists: Playlist;
    surahs: Surah;
    ayahs: Ayah;
    'hadith-collections': HadithCollection;
    hadiths: Hadith;
    'daily-reminders': DailyReminder;
    'forum-categories': ForumCategory;
    'forum-threads': ForumThread;
    'forum-posts': ForumPost;
    'forum-reactions': ForumReaction;
    reports: Report;
    enrollments: Enrollment;
    'lesson-progress': LessonProgress;
    bookmarks: Bookmark;
    notifications: Notification;
    'answer-votes': AnswerVote;
    'newsletter-subscribers': NewsletterSubscriber;
    volunteers: Volunteer;
    'contact-messages': ContactMessage;
    pages: Page;
    media: Media;
    avatars: Avatar;
    'audit-logs': AuditLog;
    'rate-limits': RateLimit1;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      account: 'accounts';
      session: 'sessions';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    accounts: AccountsSelect<false> | AccountsSelect<true>;
    verifications: VerificationsSelect<false> | VerificationsSelect<true>;
    rateLimit: RateLimitSelect<false> | RateLimitSelect<true>;
    'admin-invitations': AdminInvitationsSelect<false> | AdminInvitationsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'ikhtilaf-topics': IkhtilafTopicsSelect<false> | IkhtilafTopicsSelect<true>;
    questions: QuestionsSelect<false> | QuestionsSelect<true>;
    series: SeriesSelect<false> | SeriesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    lessons: LessonsSelect<false> | LessonsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'event-registrations': EventRegistrationsSelect<false> | EventRegistrationsSelect<true>;
    circles: CirclesSelect<false> | CirclesSelect<true>;
    'circle-meetups': CircleMeetupsSelect<false> | CircleMeetupsSelect<true>;
    'circle-memberships': CircleMembershipsSelect<false> | CircleMembershipsSelect<true>;
    'meetup-rsvps': MeetupRsvpsSelect<false> | MeetupRsvpsSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    playlists: PlaylistsSelect<false> | PlaylistsSelect<true>;
    surahs: SurahsSelect<false> | SurahsSelect<true>;
    ayahs: AyahsSelect<false> | AyahsSelect<true>;
    'hadith-collections': HadithCollectionsSelect<false> | HadithCollectionsSelect<true>;
    hadiths: HadithsSelect<false> | HadithsSelect<true>;
    'daily-reminders': DailyRemindersSelect<false> | DailyRemindersSelect<true>;
    'forum-categories': ForumCategoriesSelect<false> | ForumCategoriesSelect<true>;
    'forum-threads': ForumThreadsSelect<false> | ForumThreadsSelect<true>;
    'forum-posts': ForumPostsSelect<false> | ForumPostsSelect<true>;
    'forum-reactions': ForumReactionsSelect<false> | ForumReactionsSelect<true>;
    reports: ReportsSelect<false> | ReportsSelect<true>;
    enrollments: EnrollmentsSelect<false> | EnrollmentsSelect<true>;
    'lesson-progress': LessonProgressSelect<false> | LessonProgressSelect<true>;
    bookmarks: BookmarksSelect<false> | BookmarksSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'answer-votes': AnswerVotesSelect<false> | AnswerVotesSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    volunteers: VolunteersSelect<false> | VolunteersSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    avatars: AvatarsSelect<false> | AvatarsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'rate-limits': RateLimitsSelect<false> | RateLimitsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'about-page': AboutPage;
    'adab-policy': AdabPolicy;
    'moderation-settings': ModerationSetting;
    integrations: Integration;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'adab-policy': AdabPolicySelect<false> | AdabPolicySelect<true>;
    'moderation-settings': ModerationSettingsSelect<false> | ModerationSettingsSelect<true>;
    integrations: IntegrationsSelect<false> | IntegrationsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  email: string;
  /**
   * ইমেইলের লিংকে ক্লিক করে ঠিকানা নিশ্চিত করেছেন কিনা।
   */
  emailVerified: boolean;
  /**
   * প্রোফাইল ছবি থেকে নিজে থেকে বসে।
   */
  image?: string | null;
  createdAt: string;
  updatedAt: string;
  /**
   * শুধু শূরা ও সুপার অ্যাডমিন ভূমিকা বদলাতে পারেন।
   */
  role?: ('super_admin' | 'shura' | 'reviewer' | 'editor' | 'author' | 'moderator' | 'member')[] | null;
  /**
   * ব্যান করা ইউজার লগইন করতে পারবেন না।
   */
  banned?: boolean | null;
  banReason?: string | null;
  /**
   * খালি থাকলে ব্যান স্থায়ী।
   */
  banExpires?: string | null;
  phoneNumber?: string | null;
  phoneNumberVerified?: boolean | null;
  username?: string | null;
  journeyStage?: ('kalema' | 'iman' | 'ilm' | 'amal' | 'tazkiyah' | 'akhlaq' | 'ukhuwwah' | 'unity') | null;
  avatarColor?: ('teal' | 'gold' | 'sage' | 'deep') | null;
  /**
   * সদস্য একবারই বেছে নেন, পরে বদলানো যায় না। ভুল হলে শুধু সুপার অ্যাডমিন ঠিক করতে পারেন।
   */
  gender?: ('male' | 'female') | null;
  deletionRequestedAt?: string | null;
  account?: {
    docs?: (number | Account)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  session?: {
    docs?: (number | Session)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  district?:
    | (
        | 'dhaka'
        | 'gazipur'
        | 'narayanganj'
        | 'narsingdi'
        | 'manikganj'
        | 'munshiganj'
        | 'tangail'
        | 'kishoreganj'
        | 'faridpur'
        | 'gopalganj'
        | 'madaripur'
        | 'rajbari'
        | 'shariatpur'
        | 'chattogram'
        | 'coxs-bazar'
        | 'cumilla'
        | 'feni'
        | 'noakhali'
        | 'lakshmipur'
        | 'chandpur'
        | 'brahmanbaria'
        | 'rangamati'
        | 'khagrachhari'
        | 'bandarban'
        | 'rajshahi'
        | 'natore'
        | 'naogaon'
        | 'chapainawabganj'
        | 'pabna'
        | 'sirajganj'
        | 'bogura'
        | 'joypurhat'
        | 'khulna'
        | 'bagerhat'
        | 'satkhira'
        | 'jashore'
        | 'jhenaidah'
        | 'magura'
        | 'narail'
        | 'kushtia'
        | 'chuadanga'
        | 'meherpur'
        | 'barishal'
        | 'patuakhali'
        | 'bhola'
        | 'pirojpur'
        | 'jhalokati'
        | 'barguna'
        | 'sylhet'
        | 'moulvibazar'
        | 'habiganj'
        | 'sunamganj'
        | 'rangpur'
        | 'dinajpur'
        | 'thakurgaon'
        | 'panchagarh'
        | 'nilphamari'
        | 'lalmonirhat'
        | 'kurigram'
        | 'gaibandha'
        | 'mymensingh'
        | 'jamalpur'
        | 'sherpur'
        | 'netrokona'
      )
    | null;
  bio?: string | null;
  interests?: ('writing' | 'dawah' | 'translation' | 'tech' | 'events')[] | null;
  /**
   * স্টাফের লেখা ও রিভিউ যে প্রোফাইলে দেখাবে।
   */
  person?: (number | null) | Person;
  /**
   * শুধু ভাইদের জন্য। সদস্য নিজের সেটিংস থেকে বদলান।
   */
  avatar?: (number | null) | Avatar;
  /**
   * প্রোফাইলের কভারে সদস্যের বেছে নেওয়া আয়াত, হাদিস বা লেখা।
   */
  cover?: {
    kind?: ('none' | 'ayah' | 'hadith' | 'text') | null;
    ayahKey?: string | null;
    hadithKey?: string | null;
    text?: string | null;
    source?: string | null;
  };
  privacy?: {
    visibility?: ('public' | 'members' | 'custom' | 'private') | null;
    allowedViewers?: (number | User)[] | null;
    profilePublic?: boolean | null;
    showPhoto?: boolean | null;
    showCover?: boolean | null;
    showBio?: boolean | null;
    showDistrict?: boolean | null;
    showActivity?: boolean | null;
    showJourney?: boolean | null;
    discoverable?: boolean | null;
  };
  notificationPrefs?: {
    answer?: {
      email?: boolean | null;
      site?: boolean | null;
    };
    event?: {
      email?: boolean | null;
      site?: boolean | null;
    };
    forum?: {
      email?: boolean | null;
      site?: boolean | null;
    };
    weekly?: {
      email?: boolean | null;
      site?: boolean | null;
    };
    course?: {
      email?: boolean | null;
      site?: boolean | null;
    };
  };
  forumStats?: {
    approvedPosts?: number | null;
    trusted?: boolean | null;
    mutedUntil?: string | null;
  };
  lastActiveAt?: string | null;
  collection: 'users';
}
/**
 * Accounts are used to store user accounts for authentication providers
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts".
 */
export interface Account {
  id: number;
  accountId: string;
  providerId: string;
  user: number | User;
  accessToken?: string | null;
  refreshToken?: string | null;
  idToken?: string | null;
  accessTokenExpiresAt?: string | null;
  refreshTokenExpiresAt?: string | null;
  scope?: string | null;
  password?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * Sessions are active sessions for users. They are used to authenticate users with a session token
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: number;
  expiresAt: string;
  token: string;
  createdAt: string;
  updatedAt: string;
  ipAddress?: string | null;
  userAgent?: string | null;
  user: number | User;
  impersonatedBy?: (number | null) | User;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  name: string;
  avatarTone?: ('teal' | 'gold') | null;
  /**
   * ইংরেজি ছোট হাতের অক্ষর ও হাইফেন, যেমন: sunnah-of-respectful-disagreement
   */
  slug?: string | null;
  kinds: ('scholar' | 'author' | 'reviewer' | 'speaker')[];
  title?: string | null;
  specialty?: string | null;
  /**
   * শূরা সদস্য হলে পূরণ করুন; “আমাদের পরিচয়” পাতায় দেখাবে।
   */
  shuraRole?: string | null;
  shuraOrder?: number | null;
  verified?: boolean | null;
  active?: boolean | null;
  /**
   * ডিজাইন নীতি অনুযায়ী সাধারণত আদ্যক্ষর ব্যবহৃত হয়।
   */
  photo?: (number | null) | Media;
  user?: (number | null) | User;
  bio?: string | null;
  joinedLabel?: string | null;
  location?: string | null;
  education?:
    | {
        degree: string;
        institution?: string | null;
        id?: string | null;
      }[]
    | null;
  expertise?: string[] | null;
  roleNotes?:
    | {
        role: 'author' | 'reviewer' | 'speaker';
        note: string;
        id?: string | null;
      }[]
    | null;
  /**
   * যেমন: “ইনি আলিম প্যানেলের সদস্য নন; প্রতিটি লেখা প্যানেলের আলিম রিভিউ করেন।”
   */
  disclaimer?: string | null;
  searchText?: string | null;
  articleCount?: number | null;
  answerCount?: number | null;
  lectureCount?: number | null;
  reviewedCount?: number | null;
  eventTalkCount?: number | null;
  seriesCount?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  credit?: string | null;
  folder?: ('auto' | 'articles' | 'events' | 'courses' | 'people' | 'circles' | 'site') | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avatars".
 */
export interface Avatar {
  id: number;
  user: number | User;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    sm?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    md?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    lg?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Verifications are used to verify authentication requests
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verifications".
 */
export interface Verification {
  id: number;
  identifier: string;
  value: string;
  expiresAt: string;
  createdAt: string;
  updatedAt: string;
}
/**
 * Rate limits for users
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rateLimit".
 */
export interface RateLimit {
  id: number;
  key: string;
  count: number;
  lastRequest: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-invitations".
 */
export interface AdminInvitation {
  id: number;
  role: 'super_admin' | 'shura' | 'reviewer' | 'editor' | 'author' | 'moderator' | 'member';
  token: string;
  expiresAt: string;
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  references?:
    | {
        type: 'quran' | 'hadith' | 'ikhtilaf' | 'athar' | 'book' | 'other';
        citation: string;
        note?: string | null;
        /**
         * সাইটের ভেতরের লিংক হলে /ikhtilaf/... এভাবে লিখুন
         */
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  category: number | Category;
  author: number | Person;
  tags?: (number | Tag)[] | null;
  series?: (number | null) | Series;
  seriesOrder?: number | null;
  relatedArticles?: (number | Article)[] | null;
  coverImage?: (number | null) | Media;
  /**
   * ইংরেজি ছোট হাতের অক্ষর ও হাইফেন, যেমন: sunnah-of-respectful-disagreement
   */
  slug?: string | null;
  level: 'beginner' | 'intermediate' | 'advanced';
  tint?: ('sage' | 'gold' | 'teal') | null;
  publishedAt?: string | null;
  reviewedBy?: (number | Person)[] | null;
  readingTime?: number | null;
  reviewStatus: 'draft' | 'in_review' | 'needs_changes' | 'approved' | 'published';
  /**
   * খালি রাখলে সব রিভিউয়ারকে জানানো হবে।
   */
  assignedReviewers?: (number | User)[] | null;
  createdBy?: (number | null) | User;
  publishedBy?: (number | null) | User;
  approvals?:
    | {
        reviewer: number | User;
        decision: 'approved' | 'changes_requested';
        note?: string | null;
        contentHash?: string | null;
        at: string;
        id?: string | null;
      }[]
    | null;
  contentHash?: string | null;
  searchText?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * ইংরেজি ছোট হাতের অক্ষর ও হাইফেন, যেমন: sunnah-of-respectful-disagreement
   */
  slug?: string | null;
  description?: string | null;
  icon?:
    | (
        | 'compass'
        | 'scale'
        | 'sunrise'
        | 'sprout'
        | 'heart'
        | 'wallet'
        | 'users'
        | 'book'
        | 'columns'
        | 'home'
        | 'landmark'
        | 'mic'
      )
    | null;
  usedFor: ('articles' | 'questions' | 'videos' | 'events' | 'ikhtilaf')[];
  order?: number | null;
  articleCount?: number | null;
  questionCount?: number | null;
  videoCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  /**
   * ইংরেজি ছোট হাতের অক্ষর ও হাইফেন, যেমন: sunnah-of-respectful-disagreement
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "series".
 */
export interface Series {
  id: number;
  title: string;
  /**
   * ইংরেজি ছোট হাতের অক্ষর ও হাইফেন, যেমন: sunnah-of-respectful-disagreement
   */
  slug?: string | null;
  description?: string | null;
  author: number | Person;
  plannedParts?: number | null;
  articleCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ikhtilaf-topics".
 */
export interface IkhtilafTopic {
  id: number;
  title: string;
  lead: string;
  category: number | Category;
  subTopic?: string | null;
  readFirst?: string | null;
  consensus?:
    | {
        point: string;
        id?: string | null;
      }[]
    | null;
  opinions: {
    title: string;
    holders: string;
    evidence: {
      kind?: ('hadith' | 'ayah') | null;
      arabic?: string | null;
      text: string;
      narrator?: string | null;
      source: string;
      grade?: ('sahih' | 'hasan' | 'daif' | 'mawdu' | 'unknown') | null;
      gradeNote?: string | null;
    };
    understanding?: string | null;
    /**
     * যেমন: বুখারী : ৭৩৫
     */
    citations?: string[] | null;
    id?: string | null;
  }[];
  conduct: {
    point: string;
    id?: string | null;
  }[];
  references?:
    | {
        type: 'quran' | 'hadith' | 'ikhtilaf' | 'athar' | 'book' | 'other';
        citation: string;
        note?: string | null;
        /**
         * সাইটের ভেতরের লিংক হলে /ikhtilaf/... এভাবে লিখুন
         */
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  relatedTopics?: (number | IkhtilafTopic)[] | null;
  /**
   * ইংরেজি ছোট হাতের অক্ষর ও হাইফেন, যেমন: sunnah-of-respectful-disagreement
   */
  slug?: string | null;
  level: 'beginner' | 'intermediate' | 'advanced';
  publishedAt?: string | null;
  reviewNote?: string | null;
  reviewedBy?: (number | Person)[] | null;
  readingTime?: number | null;
  reviewStatus: 'draft' | 'in_review' | 'needs_changes' | 'approved' | 'published';
  /**
   * খালি রাখলে সব রিভিউয়ারকে জানানো হবে।
   */
  assignedReviewers?: (number | User)[] | null;
  createdBy?: (number | null) | User;
  publishedBy?: (number | null) | User;
  approvals?:
    | {
        reviewer: number | User;
        decision: 'approved' | 'changes_requested';
        note?: string | null;
        contentHash?: string | null;
        at: string;
        id?: string | null;
      }[]
    | null;
  contentHash?: string | null;
  searchText?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions".
 */
export interface Question {
  id: number;
  title: string;
  body?: string | null;
  category: number | Category;
  subTopic?: string | null;
  askedBy?: (number | null) | User;
  anonymous?: boolean | null;
  askerDistrict?:
    | (
        | 'dhaka'
        | 'gazipur'
        | 'narayanganj'
        | 'narsingdi'
        | 'manikganj'
        | 'munshiganj'
        | 'tangail'
        | 'kishoreganj'
        | 'faridpur'
        | 'gopalganj'
        | 'madaripur'
        | 'rajbari'
        | 'shariatpur'
        | 'chattogram'
        | 'coxs-bazar'
        | 'cumilla'
        | 'feni'
        | 'noakhali'
        | 'lakshmipur'
        | 'chandpur'
        | 'brahmanbaria'
        | 'rangamati'
        | 'khagrachhari'
        | 'bandarban'
        | 'rajshahi'
        | 'natore'
        | 'naogaon'
        | 'chapainawabganj'
        | 'pabna'
        | 'sirajganj'
        | 'bogura'
        | 'joypurhat'
        | 'khulna'
        | 'bagerhat'
        | 'satkhira'
        | 'jashore'
        | 'jhenaidah'
        | 'magura'
        | 'narail'
        | 'kushtia'
        | 'chuadanga'
        | 'meherpur'
        | 'barishal'
        | 'patuakhali'
        | 'bhola'
        | 'pirojpur'
        | 'jhalokati'
        | 'barguna'
        | 'sylhet'
        | 'moulvibazar'
        | 'habiganj'
        | 'sunamganj'
        | 'rangpur'
        | 'dinajpur'
        | 'thakurgaon'
        | 'panchagarh'
        | 'nilphamari'
        | 'lalmonirhat'
        | 'kurigram'
        | 'gaibandha'
        | 'mymensingh'
        | 'jamalpur'
        | 'sherpur'
        | 'netrokona'
      )
    | null;
  answeredBy?: (number | null) | Person;
  answer?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  references?:
    | {
        type: 'quran' | 'hadith' | 'ikhtilaf' | 'athar' | 'book' | 'other';
        citation: string;
        note?: string | null;
        /**
         * সাইটের ভেতরের লিংক হলে /ikhtilaf/... এভাবে লিখুন
         */
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  relatedQuestions?: (number | Question)[] | null;
  /**
   * ইংরেজি ছোট হাতের অক্ষর ও হাইফেন, যেমন: sunnah-of-respectful-disagreement
   */
  slug?: string | null;
  moderation: 'pending' | 'accepted' | 'rejected' | 'duplicate';
  moderationNote?: string | null;
  assignedTo?: (number | null) | User;
  publishedAt?: string | null;
  reviewedBy?: (number | Person)[] | null;
  answerExcerpt?: string | null;
  helpfulYes?: number | null;
  helpfulNo?: number | null;
  reviewStatus: 'draft' | 'in_review' | 'needs_changes' | 'approved' | 'published';
  /**
   * খালি রাখলে সব রিভিউয়ারকে জানানো হবে।
   */
  assignedReviewers?: (number | User)[] | null;
  createdBy?: (number | null) | User;
  publishedBy?: (number | null) | User;
  approvals?:
    | {
        reviewer: number | User;
        decision: 'approved' | 'changes_requested';
        note?: string | null;
        contentHash?: string | null;
        at: string;
        id?: string | null;
      }[]
    | null;
  contentHash?: string | null;
  searchText?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  description: string;
  journeyStage: 'kalema' | 'iman' | 'ilm' | 'amal' | 'tazkiyah' | 'akhlaq' | 'ukhuwwah' | 'unity';
  instructor?: (number | null) | Person;
  /**
   * পাঠগুলো “পাঠ” সংগ্রহে তৈরি করে মডিউল নম্বর দিয়ে যুক্ত করুন।
   */
  modules?:
    | {
        title: string;
        summary?: string | null;
        id?: string | null;
      }[]
    | null;
  durationMinutes?: number | null;
  /**
   * ইংরেজি ছোট হাতের অক্ষর ও হাইফেন, যেমন: sunnah-of-respectful-disagreement
   */
  slug?: string | null;
  level: 'beginner' | 'intermediate' | 'advanced';
  tint?: ('sage' | 'gold' | 'teal') | null;
  order?: number | null;
  status?: ('draft' | 'published') | null;
  reviewedBy?: (number | Person)[] | null;
  lessonCount?: number | null;
  enrolledCount?: number | null;
  searchText?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons".
 */
export interface Lesson {
  id: number;
  title: string;
  course: number | Course;
  module: number;
  order: number;
  media?: {
    kind?: ('none' | 'youtube' | 'audio') | null;
    youtubeId?: string | null;
    audio?: (number | null) | Media;
    durationSeconds?: number | null;
  };
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  quiz?:
    | {
        question: string;
        options?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        correctIndex: number;
        explanation?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * ইংরেজি ছোট হাতের অক্ষর ও হাইফেন, যেমন: sunnah-of-respectful-disagreement
   */
  slug?: string | null;
  durationMinutes?: number | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  summary: string;
  startsAt: string;
  endsAt?: string | null;
  /**
   * যেমন: বাদ আসর থেকে মাগরিব পর্যন্ত। খালি রাখলে সময় স্বয়ংক্রিয়ভাবে দেখাবে।
   */
  timeLabel?: string | null;
  mode: 'online' | 'in_person';
  district?:
    | (
        | 'dhaka'
        | 'gazipur'
        | 'narayanganj'
        | 'narsingdi'
        | 'manikganj'
        | 'munshiganj'
        | 'tangail'
        | 'kishoreganj'
        | 'faridpur'
        | 'gopalganj'
        | 'madaripur'
        | 'rajbari'
        | 'shariatpur'
        | 'chattogram'
        | 'coxs-bazar'
        | 'cumilla'
        | 'feni'
        | 'noakhali'
        | 'lakshmipur'
        | 'chandpur'
        | 'brahmanbaria'
        | 'rangamati'
        | 'khagrachhari'
        | 'bandarban'
        | 'rajshahi'
        | 'natore'
        | 'naogaon'
        | 'chapainawabganj'
        | 'pabna'
        | 'sirajganj'
        | 'bogura'
        | 'joypurhat'
        | 'khulna'
        | 'bagerhat'
        | 'satkhira'
        | 'jashore'
        | 'jhenaidah'
        | 'magura'
        | 'narail'
        | 'kushtia'
        | 'chuadanga'
        | 'meherpur'
        | 'barishal'
        | 'patuakhali'
        | 'bhola'
        | 'pirojpur'
        | 'jhalokati'
        | 'barguna'
        | 'sylhet'
        | 'moulvibazar'
        | 'habiganj'
        | 'sunamganj'
        | 'rangpur'
        | 'dinajpur'
        | 'thakurgaon'
        | 'panchagarh'
        | 'nilphamari'
        | 'lalmonirhat'
        | 'kurigram'
        | 'gaibandha'
        | 'mymensingh'
        | 'jamalpur'
        | 'sherpur'
        | 'netrokona'
      )
    | null;
  category?: (number | null) | Category;
  venueName?: string | null;
  venueAddress?: string | null;
  mapUrl?: string | null;
  /**
   * শুধু রেজিস্টার করা ব্যক্তিরা ইমেইলে পাবেন; পাবলিক পাতায় দেখানো হয় না।
   */
  onlineUrl?: string | null;
  audience?: string | null;
  separateSeating?: boolean | null;
  allowGuests?: boolean | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  agenda?:
    | {
        time: string;
        item: string;
        id?: string | null;
      }[]
    | null;
  speakers?: (number | Person)[] | null;
  /**
   * যেমন: “বোনদের অংশে আলোচনা”। আলোচকের ক্রম অনুযায়ী।
   */
  speakerNotes?:
    | {
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * ইংরেজি ছোট হাতের অক্ষর ও হাইফেন, যেমন: sunnah-of-respectful-disagreement
   */
  slug?: string | null;
  capacity: number;
  /**
   * মসজিদ বা সহযোগী প্রতিষ্ঠানের মাধ্যমে অফলাইনে নিশ্চিত আসন।
   */
  reservedSeats?: number | null;
  registrationOpen?: boolean | null;
  isFree?: boolean | null;
  circle?: (number | null) | Circle;
  status?: ('draft' | 'published') | null;
  seatsTaken?: number | null;
  registrationCount?: number | null;
  reminderSentAt?: string | null;
  searchText?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "circles".
 */
export interface Circle {
  id: number;
  name: string;
  district:
    | 'dhaka'
    | 'gazipur'
    | 'narayanganj'
    | 'narsingdi'
    | 'manikganj'
    | 'munshiganj'
    | 'tangail'
    | 'kishoreganj'
    | 'faridpur'
    | 'gopalganj'
    | 'madaripur'
    | 'rajbari'
    | 'shariatpur'
    | 'chattogram'
    | 'coxs-bazar'
    | 'cumilla'
    | 'feni'
    | 'noakhali'
    | 'lakshmipur'
    | 'chandpur'
    | 'brahmanbaria'
    | 'rangamati'
    | 'khagrachhari'
    | 'bandarban'
    | 'rajshahi'
    | 'natore'
    | 'naogaon'
    | 'chapainawabganj'
    | 'pabna'
    | 'sirajganj'
    | 'bogura'
    | 'joypurhat'
    | 'khulna'
    | 'bagerhat'
    | 'satkhira'
    | 'jashore'
    | 'jhenaidah'
    | 'magura'
    | 'narail'
    | 'kushtia'
    | 'chuadanga'
    | 'meherpur'
    | 'barishal'
    | 'patuakhali'
    | 'bhola'
    | 'pirojpur'
    | 'jhalokati'
    | 'barguna'
    | 'sylhet'
    | 'moulvibazar'
    | 'habiganj'
    | 'sunamganj'
    | 'rangpur'
    | 'dinajpur'
    | 'thakurgaon'
    | 'panchagarh'
    | 'nilphamari'
    | 'lalmonirhat'
    | 'kurigram'
    | 'gaibandha'
    | 'mymensingh'
    | 'jamalpur'
    | 'sherpur'
    | 'netrokona';
  type: 'brothers' | 'sisters' | 'family';
  area?: string | null;
  focus: string;
  frequency: 'weekly' | 'fortnightly' | 'monthly';
  scheduleLabel: string;
  description: string;
  venue?: string | null;
  sinceLabel?: string | null;
  memberUnit?: ('people' | 'families') | null;
  format?:
    | {
        title: string;
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  rules?:
    | {
        rule: string;
        id?: string | null;
      }[]
    | null;
  team?:
    | {
        name: string;
        role: string;
        user?: (number | null) | User;
        id?: string | null;
      }[]
    | null;
  /**
   * ইংরেজি ছোট হাতের অক্ষর ও হাইফেন, যেমন: sunnah-of-respectful-disagreement
   */
  slug?: string | null;
  coordinator?: (number | null) | User;
  status?: ('draft' | 'published') | null;
  /**
   * যাঁরা নিয়মিত আসেন কিন্তু অ্যাকাউন্ট নেই।
   */
  offlineMembers?: number | null;
  memberCount?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-registrations".
 */
export interface EventRegistration {
  id: number;
  event: number | Event;
  user?: (number | null) | User;
  code: string;
  name: string;
  phone: string;
  email?: string | null;
  seating?: ('brothers' | 'sisters') | null;
  guests?: number | null;
  status?: ('confirmed' | 'cancelled') | null;
  reminderSentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "circle-meetups".
 */
export interface CircleMeetup {
  id: number;
  circle: number | Circle;
  startsAt: string;
  topic: string;
  meta?: string | null;
  attendingCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "circle-memberships".
 */
export interface CircleMembership {
  id: number;
  circle: number | Circle;
  user: number | User;
  message?: string | null;
  status?: ('pending' | 'approved' | 'rejected' | 'cancelled') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "meetup-rsvps".
 */
export interface MeetupRsvp {
  id: number;
  meetup: number | CircleMeetup;
  user: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  title: string;
  /**
   * খালি রাখলে মূল শিরোনাম দেখাবে।
   */
  shortTitle?: string | null;
  youtubeId: string;
  speaker: number | Person;
  category: number | Category;
  playlist?: (number | null) | Playlist;
  episode?: number | null;
  durationSeconds: number;
  description?: string | null;
  chapters?:
    | {
        start: number;
        title: string;
        id?: string | null;
      }[]
    | null;
  references?:
    | {
        type: 'quran' | 'hadith' | 'ikhtilaf' | 'athar' | 'book' | 'other';
        citation: string;
        note?: string | null;
        /**
         * সাইটের ভেতরের লিংক হলে /ikhtilaf/... এভাবে লিখুন
         */
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  relatedArticles?: (number | Article)[] | null;
  /**
   * ইংরেজি ছোট হাতের অক্ষর ও হাইফেন, যেমন: sunnah-of-respectful-disagreement
   */
  slug?: string | null;
  level: 'beginner' | 'intermediate' | 'advanced';
  tint?: ('teal' | 'deep' | 'umber' | 'slate') | null;
  publishedAt?: string | null;
  /**
   * ইউটিউব থেকে হালনাগাদ করা সংখ্যা
   */
  viewCount?: number | null;
  reviewed?: boolean | null;
  status?: ('draft' | 'published') | null;
  searchText?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "playlists".
 */
export interface Playlist {
  id: number;
  title: string;
  /**
   * ইংরেজি ছোট হাতের অক্ষর ও হাইফেন, যেমন: sunnah-of-respectful-disagreement
   */
  slug?: string | null;
  description?: string | null;
  speakerLabel?: string | null;
  level?: ('beginner' | 'intermediate' | 'advanced') | null;
  tint?: ('teal' | 'deep' | 'umber' | 'slate') | null;
  order?: number | null;
  videoCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surahs".
 */
export interface Surah {
  id: number;
  number: number;
  nameArabic: string;
  nameBangla: string;
  nameLatin: string;
  meaning?: string | null;
  revelation?: ('meccan' | 'medinan') | null;
  ayahCount: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ayahs".
 */
export interface Ayah {
  id: number;
  surah: number;
  ayah: number;
  juz?: number | null;
  key?: string | null;
  sortKey?: number | null;
  arabic: string;
  arabicPlain?: string | null;
  translation: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hadith-collections".
 */
export interface HadithCollection {
  id: number;
  slug: string;
  name: string;
  shortName: string;
  compiler?: string | null;
  order?: number | null;
  hadithCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hadiths".
 */
export interface Hadith {
  id: number;
  book: number | HadithCollection;
  number: number;
  numberLabel?: string | null;
  /**
   * যেমন bukhari:735
   */
  key: string;
  chapter?: string | null;
  narrator?: string | null;
  arabic?: string | null;
  arabicPlain?: string | null;
  text: string;
  grade?: ('sahih' | 'hasan' | 'daif' | 'mawdu' | 'unknown') | null;
  gradeSource?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * হোম পেজের “আজকের আয়াত ও হাদিস”। নির্দিষ্ট তারিখ দিলে সেদিন দেখাবে, নইলে তালিকা থেকে পালাক্রমে।
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "daily-reminders".
 */
export interface DailyReminder {
  id: number;
  kind: 'ayah' | 'hadith';
  /**
   * ধারাবাহিক আয়াতের জন্য শেষ আয়াতও দিতে পারেন।
   */
  ayah?: (number | null) | Ayah;
  ayahTo?: (number | null) | Ayah;
  hadith?: (number | null) | Hadith;
  /**
   * পূরণ করলে ডাটাবেসের অনুবাদের বদলে এটি দেখাবে, যেমন রিভিউকৃত সাবলীল অনুবাদ।
   */
  custom?: {
    arabic?: string | null;
    translation?: string | null;
    reference?: string | null;
    narrator?: string | null;
    grade?: ('sahih' | 'hasan' | 'daif' | 'mawdu' | 'unknown') | null;
  };
  date?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-categories".
 */
export interface ForumCategory {
  id: number;
  name: string;
  /**
   * ইংরেজি ছোট হাতের অক্ষর ও হাইফেন, যেমন: sunnah-of-respectful-disagreement
   */
  slug?: string | null;
  description?: string | null;
  order?: number | null;
  threadCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-threads".
 */
export interface ForumThread {
  id: number;
  title: string;
  /**
   * ইংরেজি ছোট হাতের অক্ষর ও হাইফেন, যেমন: sunnah-of-respectful-disagreement
   */
  slug?: string | null;
  category: number | ForumCategory;
  author?: (number | null) | User;
  anonymous?: boolean | null;
  body: string;
  status: 'published' | 'pending' | 'hidden' | 'removed';
  flagReasons?: string[] | null;
  pinned?: boolean | null;
  locked?: boolean | null;
  helpfulPost?: (number | null) | ForumPost;
  modNote?: {
    text?: string | null;
    by?: (number | null) | User;
    at?: string | null;
  };
  replyCount?: number | null;
  viewCount?: number | null;
  reportCount?: number | null;
  lastActivityAt?: string | null;
  lastReplyBy?: (number | null) | User;
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-posts".
 */
export interface ForumPost {
  id: number;
  thread: number | ForumThread;
  parent?: (number | null) | ForumPost;
  author?: (number | null) | User;
  body: string;
  arabic?: string | null;
  reference?: string | null;
  status: 'published' | 'pending' | 'hidden' | 'removed';
  flagReasons?: string[] | null;
  helpfulCount?: number | null;
  markedHelpful?: boolean | null;
  reportCount?: number | null;
  removedReason?: string | null;
  deletedAt?: string | null;
  deletedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-reactions".
 */
export interface ForumReaction {
  id: number;
  post: number | ForumPost;
  thread: number | ForumThread;
  user: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * রিপোর্টকারীর পরিচয় শুধু মডারেটররা দেখতে পান।
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports".
 */
export interface Report {
  id: number;
  targetType: 'thread' | 'post';
  thread?: (number | null) | ForumThread;
  post?: (number | null) | ForumPost;
  reporter: number | User;
  reason: 'disrespect' | 'unsourced' | 'partisan' | 'spam';
  note?: string | null;
  status: 'open' | 'actioned' | 'dismissed';
  resolution?: string | null;
  resolvedBy?: (number | null) | User;
  resolvedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments".
 */
export interface Enrollment {
  id: number;
  user: number | User;
  course: number | Course;
  completedLessons?: number | null;
  progress?: number | null;
  lastLesson?: (number | null) | Lesson;
  lastActivityAt?: string | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lesson-progress".
 */
export interface LessonProgress {
  id: number;
  user: number | User;
  lesson: number | Lesson;
  course: number | Course;
  completedAt?: string | null;
  quizAnswers?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  quizCorrect?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookmarks".
 */
export interface Bookmark {
  id: number;
  user: number | User;
  target:
    | {
        relationTo: 'articles';
        value: number | Article;
      }
    | {
        relationTo: 'ikhtilaf-topics';
        value: number | IkhtilafTopic;
      }
    | {
        relationTo: 'videos';
        value: number | Video;
      }
    | {
        relationTo: 'questions';
        value: number | Question;
      }
    | {
        relationTo: 'ayahs';
        value: number | Ayah;
      }
    | {
        relationTo: 'hadiths';
        value: number | Hadith;
      };
  targetKey: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  recipient: number | User;
  kind: 'answer' | 'event' | 'forum' | 'course' | 'review' | 'system';
  text: string;
  link?: string | null;
  read?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "answer-votes".
 */
export interface AnswerVote {
  id: number;
  question: number | Question;
  voterKey: string;
  value: 'helpful' | 'unclear';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: number;
  email: string;
  status?: ('subscribed' | 'unsubscribed') | null;
  source?: string | null;
  user?: (number | null) | User;
  unsubscribeToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteers".
 */
export interface Volunteer {
  id: number;
  name: string;
  phone: string;
  email?: string | null;
  district:
    | 'dhaka'
    | 'gazipur'
    | 'narayanganj'
    | 'narsingdi'
    | 'manikganj'
    | 'munshiganj'
    | 'tangail'
    | 'kishoreganj'
    | 'faridpur'
    | 'gopalganj'
    | 'madaripur'
    | 'rajbari'
    | 'shariatpur'
    | 'chattogram'
    | 'coxs-bazar'
    | 'cumilla'
    | 'feni'
    | 'noakhali'
    | 'lakshmipur'
    | 'chandpur'
    | 'brahmanbaria'
    | 'rangamati'
    | 'khagrachhari'
    | 'bandarban'
    | 'rajshahi'
    | 'natore'
    | 'naogaon'
    | 'chapainawabganj'
    | 'pabna'
    | 'sirajganj'
    | 'bogura'
    | 'joypurhat'
    | 'khulna'
    | 'bagerhat'
    | 'satkhira'
    | 'jashore'
    | 'jhenaidah'
    | 'magura'
    | 'narail'
    | 'kushtia'
    | 'chuadanga'
    | 'meherpur'
    | 'barishal'
    | 'patuakhali'
    | 'bhola'
    | 'pirojpur'
    | 'jhalokati'
    | 'barguna'
    | 'sylhet'
    | 'moulvibazar'
    | 'habiganj'
    | 'sunamganj'
    | 'rangpur'
    | 'dinajpur'
    | 'thakurgaon'
    | 'panchagarh'
    | 'nilphamari'
    | 'lalmonirhat'
    | 'kurigram'
    | 'gaibandha'
    | 'mymensingh'
    | 'jamalpur'
    | 'sherpur'
    | 'netrokona';
  interests?: ('writing' | 'dawah' | 'translation' | 'tech' | 'events')[] | null;
  message?: string | null;
  user?: (number | null) | User;
  status?: ('new' | 'contacted' | 'active' | 'closed') | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  topic?: ('general' | 'correction' | 'partnership' | 'technical' | 'invite') | null;
  subject: string;
  message: string;
  user?: (number | null) | User;
  status?: ('new' | 'replied' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  lead?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * ইংরেজি ছোট হাতের অক্ষর ও হাইফেন, যেমন: sunnah-of-respectful-disagreement
   */
  slug?: string | null;
  status?: ('draft' | 'published') | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  action:
    | 'role_change'
    | 'submit'
    | 'approve'
    | 'request_changes'
    | 'publish'
    | 'unpublish'
    | 'withdraw'
    | 'moderation'
    | 'account_deletion';
  actor?: (number | null) | User;
  targetCollection?: string | null;
  targetId?: string | null;
  summary?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-limits".
 */
export interface RateLimit1 {
  id: number;
  key: string;
  count: number;
  resetAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'sessions';
        value: number | Session;
      } | null)
    | ({
        relationTo: 'accounts';
        value: number | Account;
      } | null)
    | ({
        relationTo: 'verifications';
        value: number | Verification;
      } | null)
    | ({
        relationTo: 'rateLimit';
        value: number | RateLimit;
      } | null)
    | ({
        relationTo: 'admin-invitations';
        value: number | AdminInvitation;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'ikhtilaf-topics';
        value: number | IkhtilafTopic;
      } | null)
    | ({
        relationTo: 'questions';
        value: number | Question;
      } | null)
    | ({
        relationTo: 'series';
        value: number | Series;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'lessons';
        value: number | Lesson;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'event-registrations';
        value: number | EventRegistration;
      } | null)
    | ({
        relationTo: 'circles';
        value: number | Circle;
      } | null)
    | ({
        relationTo: 'circle-meetups';
        value: number | CircleMeetup;
      } | null)
    | ({
        relationTo: 'circle-memberships';
        value: number | CircleMembership;
      } | null)
    | ({
        relationTo: 'meetup-rsvps';
        value: number | MeetupRsvp;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'playlists';
        value: number | Playlist;
      } | null)
    | ({
        relationTo: 'surahs';
        value: number | Surah;
      } | null)
    | ({
        relationTo: 'ayahs';
        value: number | Ayah;
      } | null)
    | ({
        relationTo: 'hadith-collections';
        value: number | HadithCollection;
      } | null)
    | ({
        relationTo: 'hadiths';
        value: number | Hadith;
      } | null)
    | ({
        relationTo: 'daily-reminders';
        value: number | DailyReminder;
      } | null)
    | ({
        relationTo: 'forum-categories';
        value: number | ForumCategory;
      } | null)
    | ({
        relationTo: 'forum-threads';
        value: number | ForumThread;
      } | null)
    | ({
        relationTo: 'forum-posts';
        value: number | ForumPost;
      } | null)
    | ({
        relationTo: 'forum-reactions';
        value: number | ForumReaction;
      } | null)
    | ({
        relationTo: 'reports';
        value: number | Report;
      } | null)
    | ({
        relationTo: 'enrollments';
        value: number | Enrollment;
      } | null)
    | ({
        relationTo: 'lesson-progress';
        value: number | LessonProgress;
      } | null)
    | ({
        relationTo: 'bookmarks';
        value: number | Bookmark;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'answer-votes';
        value: number | AnswerVote;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: number | NewsletterSubscriber;
      } | null)
    | ({
        relationTo: 'volunteers';
        value: number | Volunteer;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'avatars';
        value: number | Avatar;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'rate-limits';
        value: number | RateLimit1;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  emailVerified?: T;
  image?: T;
  createdAt?: T;
  updatedAt?: T;
  role?: T;
  banned?: T;
  banReason?: T;
  banExpires?: T;
  phoneNumber?: T;
  phoneNumberVerified?: T;
  username?: T;
  journeyStage?: T;
  avatarColor?: T;
  gender?: T;
  deletionRequestedAt?: T;
  account?: T;
  session?: T;
  district?: T;
  bio?: T;
  interests?: T;
  person?: T;
  avatar?: T;
  cover?:
    | T
    | {
        kind?: T;
        ayahKey?: T;
        hadithKey?: T;
        text?: T;
        source?: T;
      };
  privacy?:
    | T
    | {
        visibility?: T;
        allowedViewers?: T;
        profilePublic?: T;
        showPhoto?: T;
        showCover?: T;
        showBio?: T;
        showDistrict?: T;
        showActivity?: T;
        showJourney?: T;
        discoverable?: T;
      };
  notificationPrefs?:
    | T
    | {
        answer?:
          | T
          | {
              email?: T;
              site?: T;
            };
        event?:
          | T
          | {
              email?: T;
              site?: T;
            };
        forum?:
          | T
          | {
              email?: T;
              site?: T;
            };
        weekly?:
          | T
          | {
              email?: T;
              site?: T;
            };
        course?:
          | T
          | {
              email?: T;
              site?: T;
            };
      };
  forumStats?:
    | T
    | {
        approvedPosts?: T;
        trusted?: T;
        mutedUntil?: T;
      };
  lastActiveAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  expiresAt?: T;
  token?: T;
  createdAt?: T;
  updatedAt?: T;
  ipAddress?: T;
  userAgent?: T;
  user?: T;
  impersonatedBy?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts_select".
 */
export interface AccountsSelect<T extends boolean = true> {
  accountId?: T;
  providerId?: T;
  user?: T;
  accessToken?: T;
  refreshToken?: T;
  idToken?: T;
  accessTokenExpiresAt?: T;
  refreshTokenExpiresAt?: T;
  scope?: T;
  password?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verifications_select".
 */
export interface VerificationsSelect<T extends boolean = true> {
  identifier?: T;
  value?: T;
  expiresAt?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rateLimit_select".
 */
export interface RateLimitSelect<T extends boolean = true> {
  key?: T;
  count?: T;
  lastRequest?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-invitations_select".
 */
export interface AdminInvitationsSelect<T extends boolean = true> {
  role?: T;
  token?: T;
  expiresAt?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  content?: T;
  references?:
    | T
    | {
        type?: T;
        citation?: T;
        note?: T;
        url?: T;
        id?: T;
      };
  category?: T;
  author?: T;
  tags?: T;
  series?: T;
  seriesOrder?: T;
  relatedArticles?: T;
  coverImage?: T;
  slug?: T;
  level?: T;
  tint?: T;
  publishedAt?: T;
  reviewedBy?: T;
  readingTime?: T;
  reviewStatus?: T;
  assignedReviewers?: T;
  createdBy?: T;
  publishedBy?: T;
  approvals?:
    | T
    | {
        reviewer?: T;
        decision?: T;
        note?: T;
        contentHash?: T;
        at?: T;
        id?: T;
      };
  contentHash?: T;
  searchText?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ikhtilaf-topics_select".
 */
export interface IkhtilafTopicsSelect<T extends boolean = true> {
  title?: T;
  lead?: T;
  category?: T;
  subTopic?: T;
  readFirst?: T;
  consensus?:
    | T
    | {
        point?: T;
        id?: T;
      };
  opinions?:
    | T
    | {
        title?: T;
        holders?: T;
        evidence?:
          | T
          | {
              kind?: T;
              arabic?: T;
              text?: T;
              narrator?: T;
              source?: T;
              grade?: T;
              gradeNote?: T;
            };
        understanding?: T;
        citations?: T;
        id?: T;
      };
  conduct?:
    | T
    | {
        point?: T;
        id?: T;
      };
  references?:
    | T
    | {
        type?: T;
        citation?: T;
        note?: T;
        url?: T;
        id?: T;
      };
  relatedTopics?: T;
  slug?: T;
  level?: T;
  publishedAt?: T;
  reviewNote?: T;
  reviewedBy?: T;
  readingTime?: T;
  reviewStatus?: T;
  assignedReviewers?: T;
  createdBy?: T;
  publishedBy?: T;
  approvals?:
    | T
    | {
        reviewer?: T;
        decision?: T;
        note?: T;
        contentHash?: T;
        at?: T;
        id?: T;
      };
  contentHash?: T;
  searchText?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "questions_select".
 */
export interface QuestionsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  category?: T;
  subTopic?: T;
  askedBy?: T;
  anonymous?: T;
  askerDistrict?: T;
  answeredBy?: T;
  answer?: T;
  references?:
    | T
    | {
        type?: T;
        citation?: T;
        note?: T;
        url?: T;
        id?: T;
      };
  relatedQuestions?: T;
  slug?: T;
  moderation?: T;
  moderationNote?: T;
  assignedTo?: T;
  publishedAt?: T;
  reviewedBy?: T;
  answerExcerpt?: T;
  helpfulYes?: T;
  helpfulNo?: T;
  reviewStatus?: T;
  assignedReviewers?: T;
  createdBy?: T;
  publishedBy?: T;
  approvals?:
    | T
    | {
        reviewer?: T;
        decision?: T;
        note?: T;
        contentHash?: T;
        at?: T;
        id?: T;
      };
  contentHash?: T;
  searchText?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "series_select".
 */
export interface SeriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  author?: T;
  plannedParts?: T;
  articleCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  icon?: T;
  usedFor?: T;
  order?: T;
  articleCount?: T;
  questionCount?: T;
  videoCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  avatarTone?: T;
  slug?: T;
  kinds?: T;
  title?: T;
  specialty?: T;
  shuraRole?: T;
  shuraOrder?: T;
  verified?: T;
  active?: T;
  photo?: T;
  user?: T;
  bio?: T;
  joinedLabel?: T;
  location?: T;
  education?:
    | T
    | {
        degree?: T;
        institution?: T;
        id?: T;
      };
  expertise?: T;
  roleNotes?:
    | T
    | {
        role?: T;
        note?: T;
        id?: T;
      };
  disclaimer?: T;
  searchText?: T;
  articleCount?: T;
  answerCount?: T;
  lectureCount?: T;
  reviewedCount?: T;
  eventTalkCount?: T;
  seriesCount?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  journeyStage?: T;
  instructor?: T;
  modules?:
    | T
    | {
        title?: T;
        summary?: T;
        id?: T;
      };
  durationMinutes?: T;
  slug?: T;
  level?: T;
  tint?: T;
  order?: T;
  status?: T;
  reviewedBy?: T;
  lessonCount?: T;
  enrolledCount?: T;
  searchText?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons_select".
 */
export interface LessonsSelect<T extends boolean = true> {
  title?: T;
  course?: T;
  module?: T;
  order?: T;
  media?:
    | T
    | {
        kind?: T;
        youtubeId?: T;
        audio?: T;
        durationSeconds?: T;
      };
  content?: T;
  quiz?:
    | T
    | {
        question?: T;
        options?:
          | T
          | {
              text?: T;
              id?: T;
            };
        correctIndex?: T;
        explanation?: T;
        id?: T;
      };
  slug?: T;
  durationMinutes?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  startsAt?: T;
  endsAt?: T;
  timeLabel?: T;
  mode?: T;
  district?: T;
  category?: T;
  venueName?: T;
  venueAddress?: T;
  mapUrl?: T;
  onlineUrl?: T;
  audience?: T;
  separateSeating?: T;
  allowGuests?: T;
  description?: T;
  agenda?:
    | T
    | {
        time?: T;
        item?: T;
        id?: T;
      };
  speakers?: T;
  speakerNotes?:
    | T
    | {
        note?: T;
        id?: T;
      };
  slug?: T;
  capacity?: T;
  reservedSeats?: T;
  registrationOpen?: T;
  isFree?: T;
  circle?: T;
  status?: T;
  seatsTaken?: T;
  registrationCount?: T;
  reminderSentAt?: T;
  searchText?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-registrations_select".
 */
export interface EventRegistrationsSelect<T extends boolean = true> {
  event?: T;
  user?: T;
  code?: T;
  name?: T;
  phone?: T;
  email?: T;
  seating?: T;
  guests?: T;
  status?: T;
  reminderSentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "circles_select".
 */
export interface CirclesSelect<T extends boolean = true> {
  name?: T;
  district?: T;
  type?: T;
  area?: T;
  focus?: T;
  frequency?: T;
  scheduleLabel?: T;
  description?: T;
  venue?: T;
  sinceLabel?: T;
  memberUnit?: T;
  format?:
    | T
    | {
        title?: T;
        detail?: T;
        id?: T;
      };
  rules?:
    | T
    | {
        rule?: T;
        id?: T;
      };
  team?:
    | T
    | {
        name?: T;
        role?: T;
        user?: T;
        id?: T;
      };
  slug?: T;
  coordinator?: T;
  status?: T;
  offlineMembers?: T;
  memberCount?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "circle-meetups_select".
 */
export interface CircleMeetupsSelect<T extends boolean = true> {
  circle?: T;
  startsAt?: T;
  topic?: T;
  meta?: T;
  attendingCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "circle-memberships_select".
 */
export interface CircleMembershipsSelect<T extends boolean = true> {
  circle?: T;
  user?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "meetup-rsvps_select".
 */
export interface MeetupRsvpsSelect<T extends boolean = true> {
  meetup?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  shortTitle?: T;
  youtubeId?: T;
  speaker?: T;
  category?: T;
  playlist?: T;
  episode?: T;
  durationSeconds?: T;
  description?: T;
  chapters?:
    | T
    | {
        start?: T;
        title?: T;
        id?: T;
      };
  references?:
    | T
    | {
        type?: T;
        citation?: T;
        note?: T;
        url?: T;
        id?: T;
      };
  relatedArticles?: T;
  slug?: T;
  level?: T;
  tint?: T;
  publishedAt?: T;
  viewCount?: T;
  reviewed?: T;
  status?: T;
  searchText?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "playlists_select".
 */
export interface PlaylistsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  speakerLabel?: T;
  level?: T;
  tint?: T;
  order?: T;
  videoCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surahs_select".
 */
export interface SurahsSelect<T extends boolean = true> {
  number?: T;
  nameArabic?: T;
  nameBangla?: T;
  nameLatin?: T;
  meaning?: T;
  revelation?: T;
  ayahCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ayahs_select".
 */
export interface AyahsSelect<T extends boolean = true> {
  surah?: T;
  ayah?: T;
  juz?: T;
  key?: T;
  sortKey?: T;
  arabic?: T;
  arabicPlain?: T;
  translation?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hadith-collections_select".
 */
export interface HadithCollectionsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  shortName?: T;
  compiler?: T;
  order?: T;
  hadithCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hadiths_select".
 */
export interface HadithsSelect<T extends boolean = true> {
  book?: T;
  number?: T;
  numberLabel?: T;
  key?: T;
  chapter?: T;
  narrator?: T;
  arabic?: T;
  arabicPlain?: T;
  text?: T;
  grade?: T;
  gradeSource?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "daily-reminders_select".
 */
export interface DailyRemindersSelect<T extends boolean = true> {
  kind?: T;
  ayah?: T;
  ayahTo?: T;
  hadith?: T;
  custom?:
    | T
    | {
        arabic?: T;
        translation?: T;
        reference?: T;
        narrator?: T;
        grade?: T;
      };
  date?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-categories_select".
 */
export interface ForumCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  order?: T;
  threadCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-threads_select".
 */
export interface ForumThreadsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  author?: T;
  anonymous?: T;
  body?: T;
  status?: T;
  flagReasons?: T;
  pinned?: T;
  locked?: T;
  helpfulPost?: T;
  modNote?:
    | T
    | {
        text?: T;
        by?: T;
        at?: T;
      };
  replyCount?: T;
  viewCount?: T;
  reportCount?: T;
  lastActivityAt?: T;
  lastReplyBy?: T;
  deletedAt?: T;
  deletedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-posts_select".
 */
export interface ForumPostsSelect<T extends boolean = true> {
  thread?: T;
  parent?: T;
  author?: T;
  body?: T;
  arabic?: T;
  reference?: T;
  status?: T;
  flagReasons?: T;
  helpfulCount?: T;
  markedHelpful?: T;
  reportCount?: T;
  removedReason?: T;
  deletedAt?: T;
  deletedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forum-reactions_select".
 */
export interface ForumReactionsSelect<T extends boolean = true> {
  post?: T;
  thread?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_select".
 */
export interface ReportsSelect<T extends boolean = true> {
  targetType?: T;
  thread?: T;
  post?: T;
  reporter?: T;
  reason?: T;
  note?: T;
  status?: T;
  resolution?: T;
  resolvedBy?: T;
  resolvedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments_select".
 */
export interface EnrollmentsSelect<T extends boolean = true> {
  user?: T;
  course?: T;
  completedLessons?: T;
  progress?: T;
  lastLesson?: T;
  lastActivityAt?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lesson-progress_select".
 */
export interface LessonProgressSelect<T extends boolean = true> {
  user?: T;
  lesson?: T;
  course?: T;
  completedAt?: T;
  quizAnswers?: T;
  quizCorrect?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookmarks_select".
 */
export interface BookmarksSelect<T extends boolean = true> {
  user?: T;
  target?: T;
  targetKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  recipient?: T;
  kind?: T;
  text?: T;
  link?: T;
  read?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "answer-votes_select".
 */
export interface AnswerVotesSelect<T extends boolean = true> {
  question?: T;
  voterKey?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T;
  status?: T;
  source?: T;
  user?: T;
  unsubscribeToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "volunteers_select".
 */
export interface VolunteersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  district?: T;
  interests?: T;
  message?: T;
  user?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  topic?: T;
  subject?: T;
  message?: T;
  user?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  lead?: T;
  content?: T;
  slug?: T;
  status?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  folder?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avatars_select".
 */
export interface AvatarsSelect<T extends boolean = true> {
  user?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        sm?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        md?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        lg?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  actor?: T;
  targetCollection?: T;
  targetId?: T;
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rate-limits_select".
 */
export interface RateLimitsSelect<T extends boolean = true> {
  key?: T;
  count?: T;
  resetAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  footerBlurb: string;
  newsletterBlurb: string;
  footerAyah: {
    arabic: string;
    translation: string;
    reference: string;
  };
  contactEmail?: string | null;
  contactPhone?: string | null;
  address?: string | null;
  social?: {
    facebook?: string | null;
    youtube?: string | null;
    telegram?: string | null;
  };
  defaultTitle?: string | null;
  defaultDescription?: string | null;
  ogImage?: (number | null) | Media;
  auth?: {
    /**
     * চালু থাকলে নতুন সদস্যকে ইমেইলে পাঠানো লিংকে ক্লিক করে ঠিকানা যাচাই করতে হবে। বন্ধ করলে নিবন্ধনের সাথে সাথেই লগইন হয়ে যাবে (যাচাইয়ের ইমেইল তখন পাঠানো হয় না)। ইমেইল সেবা চালু না থাকলে বন্ধ রাখুন। লগইন লিংক, মোবাইল কোড ও Google/Facebook লগইনে এর প্রভাব নেই।
     */
    requireEmailVerification?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  heroAyah: {
    arabic: string;
    translation: string;
    reference: string;
  };
  titleLine1: string;
  titleLine2: string;
  subtitle: string;
  primaryCtaLabel: string;
  secondaryCtaLabel: string;
  support?: {
    arabic?: string | null;
    text?: string | null;
  };
  pledgeEyebrow?: string | null;
  pledgeTitle: string;
  pledges?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  journeyTitle: string;
  journeyLead?: string | null;
  journeySteps?:
    | {
        stage: 'kalema' | 'iman' | 'ilm' | 'amal' | 'tazkiyah' | 'akhlaq' | 'ukhuwwah' | 'unity';
        title: string;
        text: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  valuesTitle: string;
  valuesLead?: string | null;
  values?:
    | {
        icon: 'handshake' | 'book' | 'message' | 'search' | 'mark' | 'users';
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  featuredIkhtilaf?: (number | null) | IkhtilafTopic;
  ikhtilafPoints?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  ilmLead?: string | null;
  ctaTitle: string;
  ctaText: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  title: string;
  lead: string;
  version?: string | null;
  publishedLabel?: string | null;
  readingTime?: number | null;
  /**
   * H2 শিরোনামগুলো সূচিপত্রে দেখাবে। “আমাদের অঙ্গীকার” শিরোনামটি ঘোষণাপত্র অংশের লিংক।
   */
  manifesto: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  shuraIntro: string;
  adabIntro: string;
  adabRules?:
    | {
        icon?: ('book' | 'heart' | 'scale' | 'ban' | 'megaphone' | 'user') | null;
        tone?: ('teal' | 'gold') | null;
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  ctaTitle: string;
  ctaText: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adab-policy".
 */
export interface AdabPolicy {
  id: number;
  title: string;
  lead: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  enforcement?:
    | {
        step: string;
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "moderation-settings".
 */
export interface ModerationSetting {
  id: number;
  firstPostsModerated?: number | null;
  reportThreshold?: number | null;
  maxLinks?: number | null;
  /**
   * এই শব্দ থাকলে পোস্টটি সরাসরি প্রকাশ না হয়ে মডারেশনে যাবে।
   */
  blockedTerms?: string[] | null;
  postsPerHour?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Google ও Facebook লগইন, SMS আর ইমেইলের সেটিংস। এখানে দেওয়া মান .env-এর মানের চেয়ে অগ্রাধিকার পায় এবং সংরক্ষণের এক মিনিটের মধ্যে সাইটে কাজ শুরু করে। গোপন চাবিগুলো এনক্রিপ্ট করে রাখা হয়।
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations".
 */
export interface Integration {
  id: number;
  google?: {
    /**
     * বন্ধ করলে লগইন ও রেজিস্টার পাতা থেকে বাটনটি সরে যাবে।
     */
    enabled?: boolean | null;
    /**
     * Google Cloud Console > APIs & Services > Credentials > OAuth client ID (Web application) থেকে।
     */
    clientId?: string | null;
    /**
     * সংরক্ষণের পর আর দেখা যায় না। বদলাতে চাইলে নতুনটি লিখুন।
     */
    clientSecret?: string | null;
    clientSecretEnc?: string | null;
    clientSecretHint?: string | null;
  };
  facebook?: {
    /**
     * বন্ধ করলে লগইন ও রেজিস্টার পাতা থেকে বাটনটি সরে যাবে।
     */
    enabled?: boolean | null;
    /**
     * developers.facebook.com > আপনার অ্যাপ > App settings > Basic থেকে App ID।
     */
    clientId?: string | null;
    /**
     * সংরক্ষণের পর আর দেখা যায় না। বদলাতে চাইলে নতুনটি লিখুন।
     */
    clientSecret?: string | null;
    clientSecretEnc?: string | null;
    clientSecretHint?: string | null;
  };
  sms?: {
    /**
     * মোবাইল নম্বরে লগইন কোড পাঠাতে আসল গেটওয়ে লাগবে।
     */
    provider?: ('console' | 'bd_gateway') | null;
    /**
     * গেটওয়ের SMS পাঠানোর ঠিকানা, যেমন https://bulksmsbd.net/api/smsapi
     */
    apiUrl?: string | null;
    /**
     * গেটওয়ের প্যানেল থেকে। সংরক্ষণের পর আর দেখা যায় না।
     */
    apiKey?: string | null;
    apiKeyEnc?: string | null;
    apiKeyHint?: string | null;
    /**
     * গেটওয়েতে অনুমোদিত প্রেরকের নাম বা নম্বর।
     */
    senderId?: string | null;
  };
  email?: {
    /**
     * resend.com > API Keys থেকে। সংরক্ষণের পর আর দেখা যায় না।
     */
    resendApiKey?: string | null;
    resendApiKeyEnc?: string | null;
    resendApiKeyHint?: string | null;
    /**
     * Resend-এ যাচাই করা ডোমেইনের ঠিকানা, যেমন: Ruhama <noreply@আপনার-ডোমেইন>
     */
    from?: string | null;
    replyTo?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  footerBlurb?: T;
  newsletterBlurb?: T;
  footerAyah?:
    | T
    | {
        arabic?: T;
        translation?: T;
        reference?: T;
      };
  contactEmail?: T;
  contactPhone?: T;
  address?: T;
  social?:
    | T
    | {
        facebook?: T;
        youtube?: T;
        telegram?: T;
      };
  defaultTitle?: T;
  defaultDescription?: T;
  ogImage?: T;
  auth?:
    | T
    | {
        requireEmailVerification?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroAyah?:
    | T
    | {
        arabic?: T;
        translation?: T;
        reference?: T;
      };
  titleLine1?: T;
  titleLine2?: T;
  subtitle?: T;
  primaryCtaLabel?: T;
  secondaryCtaLabel?: T;
  support?:
    | T
    | {
        arabic?: T;
        text?: T;
      };
  pledgeEyebrow?: T;
  pledgeTitle?: T;
  pledges?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  journeyTitle?: T;
  journeyLead?: T;
  journeySteps?:
    | T
    | {
        stage?: T;
        title?: T;
        text?: T;
        href?: T;
        id?: T;
      };
  valuesTitle?: T;
  valuesLead?: T;
  values?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  featuredIkhtilaf?: T;
  ikhtilafPoints?:
    | T
    | {
        text?: T;
        id?: T;
      };
  ilmLead?: T;
  ctaTitle?: T;
  ctaText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  title?: T;
  lead?: T;
  version?: T;
  publishedLabel?: T;
  readingTime?: T;
  manifesto?: T;
  shuraIntro?: T;
  adabIntro?: T;
  adabRules?:
    | T
    | {
        icon?: T;
        tone?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  ctaTitle?: T;
  ctaText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adab-policy_select".
 */
export interface AdabPolicySelect<T extends boolean = true> {
  title?: T;
  lead?: T;
  content?: T;
  enforcement?:
    | T
    | {
        step?: T;
        detail?: T;
        id?: T;
      };
  updatedLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "moderation-settings_select".
 */
export interface ModerationSettingsSelect<T extends boolean = true> {
  firstPostsModerated?: T;
  reportThreshold?: T;
  maxLinks?: T;
  blockedTerms?: T;
  postsPerHour?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations_select".
 */
export interface IntegrationsSelect<T extends boolean = true> {
  google?:
    | T
    | {
        enabled?: T;
        clientId?: T;
        clientSecret?: T;
        clientSecretEnc?: T;
        clientSecretHint?: T;
      };
  facebook?:
    | T
    | {
        enabled?: T;
        clientId?: T;
        clientSecret?: T;
        clientSecretEnc?: T;
        clientSecretHint?: T;
      };
  sms?:
    | T
    | {
        provider?: T;
        apiUrl?: T;
        apiKey?: T;
        apiKeyEnc?: T;
        apiKeyHint?: T;
        senderId?: T;
      };
  email?:
    | T
    | {
        resendApiKey?: T;
        resendApiKeyEnc?: T;
        resendApiKeyHint?: T;
        from?: T;
        replyTo?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AyahBlock".
 */
export interface AyahBlock {
  /**
   * বাছাই করলে আরবি, অনুবাদ ও সূত্র স্বয়ংক্রিয়ভাবে আসবে। নিচের ঘরগুলো পূরণ করলে সেগুলো অগ্রাধিকার পাবে।
   */
  ayah?: (number | null) | Ayah;
  arabic?: string | null;
  translation?: string | null;
  reference?: string | null;
  compact?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ayah';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HadithBlock".
 */
export interface HadithBlock {
  hadith?: (number | null) | Hadith;
  arabic?: string | null;
  text?: string | null;
  narrator?: string | null;
  source?: string | null;
  grade?: ('sahih' | 'hasan' | 'daif' | 'mawdu' | 'unknown') | null;
  gradeNote?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hadith';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DalilBlock".
 */
export interface DalilBlock {
  title?: string | null;
  items?:
    | {
        type: 'quran' | 'hadith' | 'ikhtilaf' | 'athar' | 'book' | 'other';
        citation: string;
        note?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'dalil';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "YouTubeBlock".
 */
export interface YouTubeBlock {
  url: string;
  title: string;
  start?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'youtube';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalloutBlock".
 */
export interface CalloutBlock {
  tone?: ('note' | 'gold' | 'warning') | null;
  title?: string | null;
  body: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'callout';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PullQuoteBlock".
 */
export interface PullQuoteBlock {
  text: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pullQuote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}